### ISSUE TITLE
전투: 자잘한 버그 수정

### ISSUE THREAD

**Issue by VanSubstance** [kang123077/SlimeGG#42]
- [x] 유닛 배치 제한수를 넘겼음에도 전투 작동
유닛 배치 제한 수 = 엔트리 수이므로 몬스터 UI부분을 막아놓는 방식으로 수정 할 예정
- [x] 전투 종료 후 투사체/장판/이펙트 등, 애니메이션이 계속 재생

**Comment by kang123077** [comment]
- [ ] 배틀씬 인벤토리에 몬스터 재배치 시 사이즈 커짐
- [x] 몬스터 UI 윈도우가 메인이 되는 문제
상단의 몬스터 UI를 막아주면 해결 되는 이슈
